name: minimal_serialization_example
dependencies:
  minimal_serialization:
    git: https://github.com/alan-knight/minimal_serialization
  unittest: any
transformers:
   - minimal_serialization :
       $include: lib/test_models.dart
   - $dart2js :
       $include : foo.bar